---
title: "NYC Collision Analysis"
output: 
  html_document: 
    fig_height: 7
    fig_width: 10
    theme: journal
    toc: yes
---
The motor vehicle collision database includes the date and time, location (as borough, street names, zip code and latitude and longitude coordinates), injuries and fatalities, vehicle number and types, and related factors for all 65,500 collisions in New York City during 2015 and 2016.

## Data Import 
```{r}
# Setting Directory
# setwd("/home/milan/Documents/MachineLearning/R-workspace/Kaggle/NYC_Vehicle_collision/")

# Library Import
library(data.table)
library(plotly)
library(ggplot2)
library(ggthemes)

# Data import and Processing
collisionData <- read.csv("/home/user/Documents/R-workspace/machine-learning/NYC_Vehicle_Collision_Analysis/data/database.csv")
collisionData <- data.table(collisionData)
collisionData$DATE <- as.Date(collisionData$DATE,format = "%m/%d/%y")
str(collisionData)
tail(collisionData$DATE)
```
## Get Basic Trend
```{r, echo=TRUE, message=TRUE, warning=TRUE}
trendChart <- ggplot(collisionData)+geom_line(aes(DATE,group=1),stat="count",col="#B83238")+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red")+ggtitle("Trend Of Collision")+ylab("No of collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))
ggplotly(trendChart)
```

```{r}
trendAnalysis <- collisionData[,.N,by=DATE]
summary(trendAnalysis)
#1st Qu. 
# 488.5 

#3rd Qu. 
# 609 
  
trendWithSummary <- ggplot(trendAnalysis,aes(DATE,N))+geom_line(col="#B83238")+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red")+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))+
  geom_hline(aes(yintercept=mean(trendAnalysis$N)),colour = "green",linetype="dotted")+ 
  geom_ribbon(aes(ymin = 488.5, ymax =609), fill = "grey70",alpha = 0.2)
ggplotly(trendWithSummary)
```
Green Line - Mean 
Shaded Region - Inter Quantile Range

```{r}
library(reshape2)
InvolvedPerson <- collisionData[,.(.N,sum(PERSONS.INJURED),sum(PERSONS.KILLED)),by=DATE]
colnames(InvolvedPerson) <- c("DATE","Accident.Count","PERSONS.INJURED","PERSONS.KILLED")

InvolvedPersonMelted <- melt(InvolvedPerson,id.vars = "DATE")

trendWithSummary <- ggplot(InvolvedPerson)+geom_line(col="#B83238",aes(DATE,Accident.Count))+geom_line(col="#819FF7",aes(DATE,PERSONS.KILLED))+geom_line(col="#FF8000",aes(DATE,PERSONS.INJURED))+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red")+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of person killed | person injured | collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))+
  geom_hline(aes(yintercept=mean(trendAnalysis$N)),colour = "green",linetype="dotted")

trendWithSummary <- ggplot(InvolvedPersonMelted)+geom_line(aes(DATE,value,col= variable))+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red",guide = guide_legend(title = "Count Statistic"))+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of person killed | person injured | collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))
ggplotly(trendWithSummary)

```
```{r}

InvolvedPerson <- collisionData[,.(.N,sum(PERSONS.INJURED),sum(PERSONS.KILLED)),by=c("DATE","BOROUGH")]
colnames(InvolvedPerson) <- c("DATE","BOROUGH","Accident.Count","PERSONS.INJURED","PERSONS.KILLED")

InvolvedPersonMelted <- melt(InvolvedPerson,id.vars = c("DATE","BOROUGH"))


ggplot(InvolvedPersonMelted)+geom_line(aes(DATE,value,col= variable))+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red",guide = guide_legend(title = "Count Statistic"))+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of person killed | person injured | collision")+facet_wrap(~BOROUGH)+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))

```


```{r}
ggplot(InvolvedPerson,aes(Accident.Count,PERSONS.INJURED))+geom_point(col="#DBA901")+geom_smooth(method = "lm",colour="#31B404")+theme_solarized(light = FALSE) +
  scale_colour_solarized("red")+ggtitle("RelationShip Between Collision Count and Person Injured")+ylab("No of Person Injured")+xlab("No of Collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))

```


```{r}
collisionData <- collisionData[,HourOfCollision := strsplit(as.character(TIME),":")[[1]][1],by=1:nrow(collisionData)]
collisionData$HourOfCollision <- factor(collisionData$HourOfCollision ,levels = seq(0, 23))

ggplot(collisionData)+geom_line(aes(HourOfCollision,group=1),stat = "count",col="#FFFFFF")+theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red")+ggtitle("Trend Of Collision (Hour Based)")+ylab("No of collision")+xlab("Hour Of Collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))
ggplotly()
```


```{r}
ggplot(collisionData)+geom_line(aes(HourOfCollision,group=1),stat = "count",col="#FFFFFF")+theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red")+ggtitle("Trend Of Collision (Hour Based)")+ylab("No of collision")+xlab("Hour Of Collision")+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))+facet_wrap(~BOROUGH)
```


```{r}
InvolvedPerson <- collisionData[,.(.N,sum(PERSONS.INJURED),sum(PERSONS.KILLED)),by=c("HourOfCollision","BOROUGH")]

colnames(InvolvedPerson) <- c("Hour_Of_Collision","BOROUGH","Accident.Count","PERSONS.INJURED","PERSONS.KILLED")

InvolvedPersonMelted <- melt(InvolvedPerson,id.vars = c("Hour_Of_Collision","BOROUGH"))

ggplot(InvolvedPersonMelted)+geom_line(aes(Hour_Of_Collision,value,col= variable,group = variable))+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red",guide = guide_legend(title = "Count Statistic"))+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of person killed | person injured | collision")+facet_wrap(~BOROUGH)+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))

```
```{r}
collisionData <- collisionData[,month := month(DATE),by=1:nrow(collisionData)]
collisionData <- collisionData[,weekdays:= weekdays(DATE)]
collisionData <- collisionData[,day:= format(DATE, "%d")]

InvolvedPerson <- collisionData[,.(.N,sum(PERSONS.INJURED),sum(PERSONS.KILLED)),by=c("HourOfCollision","BOROUGH","month")]

colnames(InvolvedPerson) <- c("Hour_Of_Collision","BOROUGH","month","Accident.Count","PERSONS.INJURED","PERSONS.KILLED")

InvolvedPersonMelted <- melt(InvolvedPerson,id.vars = c("Hour_Of_Collision","BOROUGH","month"))

ggplot(InvolvedPersonMelted)+geom_line(aes(Hour_Of_Collision,value,col= variable,group = variable))+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red",guide = guide_legend(title = "Count Statistic"))+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of person killed | person injured | collision")+facet_wrap(~BOROUGH+month)+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))

ggplot(InvolvedPersonMelted)+geom_bar(aes(BOROUGH,value,fill=variable),stat = "identity",position="dodge")

```

```{r}
InvolvedPerson <- collisionData[,.(.N,sum(PERSONS.INJURED),sum(PERSONS.KILLED)),by=c("HourOfCollision","BOROUGH","month","day")]

colnames(InvolvedPerson) <- c("Hour_Of_Collision","BOROUGH","month","day","Accident.Count","PERSONS.INJURED","PERSONS.KILLED")

InvolvedPersonMelted <- melt(InvolvedPerson,id.vars = c("Hour_Of_Collision","BOROUGH","month"))

ggplot(InvolvedPersonMelted)+geom_line(aes(Hour_Of_Collision,value,col= variable,group = variable))+
  theme(axis.text.x=element_text(angle = 90))+theme_solarized(light = FALSE) +
  scale_colour_solarized("red",guide = guide_legend(title = "Count Statistic"))+ggtitle("Trend Of Collision With Statisical Summary")+ylab("No of person killed | person injured | collision")+facet_wrap(~BOROUGH+month)+
  theme(axis.title.x = element_text(colour = "white"),axis.title.y = element_text(colour = "white"),title = element_text(colour = "white"))
```
